export const PROGRESS = "PROGRESS";

export const ACTION_FORGOT_PASSWORD = "ACIION_FORGOT_PASSWORD";
export const ACTION_FORGOT_PASSWORD_SUCCESS = "ACTION_FORGOT_PASSWORD_SUCCESS";
export const ACTION_FORGOT_PASSWORD_ERROR = "ACTION_FORGOT_PASSWORD_ERROR";
export const ACTION_EMPTY_FORGOT_PASSWORD = "ACTION_EMPTY_FORGOT_PASSWORD";
export const ACTION_SIGNUP_VERIFY = "ACTION_SIGNUP_VERIFY";
export const ACTION_SIGNUP_VERIFY_SUCCESS = "ACTION_SIGNUP_VERIFY_SUCCESS";
export const ACTION_SIGNUP_VERIFY_ERROR = "ACTION_SIGNUP_VERIFY_ERROR";

export const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";

export const SHOW_MESSAGE = "SHOW_MESSAGE";
export const HIDE_MESSAGE = "HIDE_MESSAGE";

export const LOGOUT_REQUEST_SUCCESS = "session/LOGOUT_REQUEST_SUCCESS";



